server:
  port: 8083   # Le port du microservice

spring:
  application:
    name: note-service   # Nom utilisé par Eureka

  datasource:
    url: jdbc:mysql://localhost:3306/notes_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update    # Crée les tables automatiquement
    show-sql: true        # Affiche les requêtes SQL dans la console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # Adresse du serveur Eureka
    register-with-eureka: true
    fetch-registry: true
