server:
  port: 8081

spring:
  application:
    name: etudiant-service

  datasource:
    url: jdbc:mysql://localhost:3306/etudiants_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root    # change si ton mot de passe MySQL est différent

  jpa:
    hibernate:
      ddl-auto: update   # pour créer / mettre à jour les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
